CREATE TABLE blogful_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE blogful_articles
  ADD COLUMN
    author INTEGER REFERENCES blogful_users(id)
    ON DELETE SET NULL;